export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USERS_LOADING = 'USERS_LOADING';
export const USERS_LOADED = 'USERS_LOADED';
export const FRIENDS_LOADED = 'FRIENDS_LOADED';

export const USER_UPDATING = "USER_UPDATING";
export const USER_UPDATED= 'USER_UPDATED';
export const UPDATING_USER_ERROR = "UPDATING_USER_ERROR";


export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const GET_REGISTER_ERRORS = 'GET_REGISTER_ERRORS';
export const CLEAR_REGISTER_ERRORS = 'CLEAR_REGISTER_ERRORS';
export const GET_LOGIN_ERRORS = 'GET_LOGIN_ERRORS';
export const CLEAR_LOGIN_ERRORS = 'CLEAR_LOGIN_ERRORS';
export const REGISTER_LOADING = 'REGISTER_LOADING';
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const UPDATE_LOGGED_USER = "UPDATE_LOGGED_USER";
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const OPEN_LOGIN_MODAL = 'OPEN_LOGIN_MODAL';
export const CLOSE_LOGIN_MODAL = 'CLOSE_LOGIN_MODAL';
export const CLOSE_REGISTER_MODAL = 'CLOSE_REGISTER_MODAL';
export const OPEN_REGISTER_MODAL = 'OPEN_REGISTER_MODAL';
export const CLOSE_FORGOT_PASSWORD_MODAL = 'CLOSE_FORGOT_PASSWORD_MODAL';
export const OPEN_FORGOT_PASSWORD_MODAL = 'OPEN_FORGOT_PASSWORD_MODAL';
export const OPEN_ADD_POST_MODAL = 'OPEN_ADD_POST_MODAL';
export const CLOSE_ADD_POST_MODAL = 'CLOSE_ADD_POST_MODAL';
export const POSTS_LOADING = 'POSTS_LOADING';
export const GET_POSTS = "GET_POSTS";
export const ADD_POST = "ADD_POST";
export const ADD_TO_POSTS = "ADD_TO_POSTS";

export const CHAT_WITH_FRIEND = "CHAT_WITH_FRIEND";
export const STOP_CHATTING_WITH_FRIEND = "STOP_CHATTING_WITH_FRIEND";
