export const REGISTER_SUCCESS= 'REGISTER_SUCCESS';
export const REGISTER_FAIL= 'REGISTER_FAIL';
export const USER_LOADING= 'USER_LOADING';
export const USER_LOADED= 'USER_LOADED';
export const GET_ERRORS= 'GET_ERRORS';
export const CLEAR_ERRORS= 'CLEAR_ERRORS';
export const REGISTER_LOADING = 'REGISTER_LOADING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const CLOSE_LOGIN_MODAL = 'CLOSE_LOGIN_MODAL';
export const OPEN_LOGIN_MODAL = 'OPEN_LOGIN_MODAL';
export const CLOSE_REGISTER_MODAL = 'CLOSE_REGISTER_MODAL';
export const OPEN_REGISTER_MODAL = 'OPEN_REGISTER_MODAL';

export const TEST = 'TEST';